tools:

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: TYPO3CMS

    php_cs_fixer:
        enabled: true

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true